ALTER TYPE "NotificationType"
ADD VALUE IF NOT EXISTS 'PLAYER_PROFILE_VIEWED_BY_COACH';

ALTER TYPE "OwnershipMode"
ADD VALUE IF NOT EXISTS 'TEAM_PENDING';

ALTER TYPE "ProfileState"
ADD VALUE IF NOT EXISTS 'TEAM_INVITED';
