// app/lib/academics/academicAreas.ts

export const ACADEMIC_AREA_OPTIONS = [
  "Accounting",
  "Architecture",
  "Athletic Training",
  "Biology",
  "Business",
  "Chemistry",
  "Communications",
  "Computer Science",
  "Criminal Justice",
  "Data Science",
  "Economics",
  "Education",
  "Engineering",
  "Entrepreneurship",
  "Exercise Science",
  "Finance",
  "Health Sciences",
  "History",
  "Kinesiology",
  "Management",
  "Marketing",
  "Mathematics",
  "Nursing",
  "Nutrition",
  "Physical Therapy",
  "Political Science",
  "Pre-Law",
  "Pre-Med",
  "Psychology",
  "Public Health",
  "Social Work",
  "Sociology",
  "Sports Management",
  "Sports Medicine",
  "Statistics",
  "Supply Chain & Logistics",
].sort((a, b) => a.localeCompare(b));