// app/lib/academics/academicAreas.ts

export const ACADEMIC_AREA_OPTIONS = [
  "Accounting",
  "Agriculture",
  "Animal Science",
  "Architecture",
  "Art",
  "Art History",
  "Athletic Training",
  "Biology",
  "Biomedical Sciences",
  "Business",
  "Chemistry",
  "Communications",
  "Computer Science",
  "Criminal Justice",
  "Cybersecurity",
  "Data Science",
  "Economics",
  "Education",
  "Engineering",
  "Entrepreneurship",
  "Environmental Science",
  "Exercise Science",
  "Finance",
  "Graphic Design",
  "Health Sciences",
  "History",
  "Human Resources",
  "Information Technology",
  "Journalism",
  "Kinesiology",
  "Language Arts",
  "Literature",
  "Management",
  "Marine Biology",
  "Marketing",
  "Mathematics",
  "Music",
  "Nursing",
  "Nutrition",
  "Occupational Therapy",
  "Performing Arts",
  "Philosophy",
  "Physics",
  "Physical Therapy",
  "Political Science",
  "Pre-Law",
  "Pre-Med",
  "Pre-Vet",
  "Psychology",
  "Public Health",
  "Religion",
  "Respiratory Therapy",
  "Social Work",
  "Sociology",
  "Sports Management",
  "Sports Medicine",
  "Statistics",
  "Supply Chain & Logistics",
  "Theater",
  "Visual Arts",
].sort((a, b) => a.localeCompare(b));