// app/lib/academics/academicAreas.ts

export const ACADEMIC_AREA_OPTIONS = [
  "Accounting",
  "Actuarial Science",
  "Agriculture",
  "Animal Science",
  "Architecture",
  "Art",
  "Art History",
  "Athletic Training",
  "Biochemistry",
  "Biology",
  "Biomedical Engineering",
  "Biomedical Sciences",
  "Biotechnology",
  "Business",
  "Business Analytics",
  "Chemistry",
  "Civil Engineering",
  "Communications",
  "Computer Engineering",
  "Computer Science",
  "Construction Management",
  "Criminal Justice",
  "Cybersecurity",
  "Data Analytics",
  "Data Science",
  "Digital Media",
  "Economics",
  "Education",
  "Electrical Engineering",
  "Emergency Management",
  "Engineering",
  "English",
  "Entrepreneurship",
  "Environmental Science",
  "Exercise Physiology",
  "Exercise Science",
  "Film Studies",
  "Finance",
  "Forensic Science",
  "Game Design",
  "Graphic Design",
  "Health Administration",
  "Health Sciences",
  "History",
  "Hospitality",
  "Hospitality Management",
  "Human Resources",
  "Human Services",
  "Industrial Engineering",
  "Information Systems",
  "Information Technology",
  "International Business",
  "International Relations",
  "Journalism",
  "Kinesiology",
  "Language Arts",
  "Literature",
  "Management",
  "Marine Biology",
  "Marketing",
  "Mathematics",
  "Mechanical Engineering",
  "Media Studies",
  "Music",
  "Neuroscience",
  "Nursing",
  "Nutrition",
  "Occupational Therapy",
  "Performing Arts",
  "Philosophy",
  "Physical Therapy",
  "Physics",
  "Political Science",
  "Pre-Dentistry",
  "Pre-Law",
  "Pre-Med",
  "Pre-Nursing",
  "Pre-Pharmacy",
  "Pre-Physical Therapy",
  "Pre-Veterinary Medicine",
  "Pre-Vet",
  "Psychology",
  "Public Administration",
  "Public Health",
  "Public Relations",
  "Religion",
  "Respiratory Therapy",
  "Social Work",
  "Sociology",
  "Software Engineering",
  "Speech Pathology",
  "Sport Management",
  "Sports Management",
  "Sports Medicine",
  "Statistics",
  "Strength & Conditioning",
  "Supply Chain & Logistics",
  "Theater",
  "Urban Planning",
  "Veterinary Science",
  "Visual Arts",
  "Web Development",
].sort((a, b) => a.localeCompare(b));