// scripts/seed-colleges.ts

import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

type SeedCollege = {
  name: string;
  slug: string;
  websiteUrl?: string;
  admissionsUrl?: string;
  academicsUrl?: string;
  majorsUrl?: string;
  applicationUrl?: string;
  financialAidUrl?: string;
  city?: string;
  state: string;
  region?: "NORTHEAST" | "MID_ATLANTIC" | "SOUTHEAST" | "MIDWEST" | "SOUTHWEST" | "WEST" | "PACIFIC";
  control?: "PUBLIC" | "PRIVATE";
  schoolType?: "FOUR_YEAR" | "TWO_YEAR" | "COMMUNITY_COLLEGE" | "JUNIOR_COLLEGE" | "OTHER";
  tuitionInState?: number;
  tuitionOutOfState?: number;
  tuitionInternational?: number;
  tuitionYear?: number;

  baseball?: {
    nickname?: string;
    baseballWebsiteUrl?: string;
    division?: "NCAA_D1" | "NCAA_D2" | "NCAA_D3" | "NAIA" | "NJCAA_D1" | "NJCAA_D2" | "NJCAA_D3" | "OTHER";
    conference?: string;
    rosterUrl?: string;
    questionnaireUrl?: string;
  };
};

const colleges: SeedCollege[] = [
  {
    name: "University of South Carolina",
    slug: "university-of-south-carolina",
    websiteUrl: "https://www.sc.edu",
    admissionsUrl: "https://sc.edu/about/offices_and_divisions/undergraduate_admissions/",
    city: "Columbia",
    state: "SC",
    region: "SOUTHEAST",
    control: "PUBLIC",
    baseball: {
      nickname: "Gamecocks",
      baseballWebsiteUrl: "https://gamecocksonline.com/sports/baseball/",
      division: "NCAA_D1",
      conference: "SEC",
    },
  },
    {
    name: "Clemson University",
    slug: "clemson-university",
    websiteUrl: "https://www.clemson.edu",
    admissionsUrl: "https://www.clemson.edu/admissions/",
    city: "Clemson",
    state: "SC",
    region: "SOUTHEAST",
    control: "PUBLIC",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Tigers",
      baseballWebsiteUrl: "https://clemsontigers.com/sports/baseball/",
      division: "NCAA_D1",
      conference: "ACC",
    },
  },
  {
    name: "College of Charleston",
    slug: "college-of-charleston",
    websiteUrl: "https://www.charleston.edu",
    admissionsUrl: "https://www.charleston.edu/admission/",
    city: "Charleston",
    state: "SC",
    region: "SOUTHEAST",
    control: "PUBLIC",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Cougars",
      baseballWebsiteUrl: "https://cofcsports.com/sports/baseball",
      division: "NCAA_D1",
      conference: "CAA",
    },
  },
  {
    name: "Wofford College",
    slug: "wofford-college",
    websiteUrl: "https://www.wofford.edu",
    admissionsUrl: "https://www.wofford.edu/admission",
    city: "Spartanburg",
    state: "SC",
    region: "SOUTHEAST",
    control: "PRIVATE",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Terriers",
      baseballWebsiteUrl: "https://woffordterriers.com/sports/baseball",
      division: "NCAA_D1",
      conference: "SoCon",
    },
  },
  {
    name: "Winthrop University",
    slug: "winthrop-university",
    websiteUrl: "https://www.winthrop.edu",
    admissionsUrl: "https://www.winthrop.edu/admissions/",
    city: "Rock Hill",
    state: "SC",
    region: "SOUTHEAST",
    control: "PUBLIC",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Eagles",
      baseballWebsiteUrl: "https://winthropeagles.com/sports/baseball",
      division: "NCAA_D1",
      conference: "Big South",
    },
  },
  {
    name: "University of North Carolina at Chapel Hill",
    slug: "university-of-north-carolina-at-chapel-hill",
    websiteUrl: "https://www.unc.edu",
    admissionsUrl: "https://admissions.unc.edu",
    city: "Chapel Hill",
    state: "NC",
    region: "SOUTHEAST",
    control: "PUBLIC",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Tar Heels",
      baseballWebsiteUrl: "https://goheels.com/sports/baseball",
      division: "NCAA_D1",
      conference: "ACC",
    },
  },
  {
    name: "North Carolina State University",
    slug: "north-carolina-state-university",
    websiteUrl: "https://www.ncsu.edu",
    admissionsUrl: "https://admissions.ncsu.edu",
    city: "Raleigh",
    state: "NC",
    region: "SOUTHEAST",
    control: "PUBLIC",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Wolfpack",
      baseballWebsiteUrl: "https://gopack.com/sports/baseball",
      division: "NCAA_D1",
      conference: "ACC",
    },
  },
  {
    name: "Duke University",
    slug: "duke-university",
    websiteUrl: "https://www.duke.edu",
    admissionsUrl: "https://admissions.duke.edu",
    city: "Durham",
    state: "NC",
    region: "SOUTHEAST",
    control: "PRIVATE",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Blue Devils",
      baseballWebsiteUrl: "https://goduke.com/sports/baseball",
      division: "NCAA_D1",
      conference: "ACC",
    },
  },
  {
    name: "East Carolina University",
    slug: "east-carolina-university",
    websiteUrl: "https://www.ecu.edu",
    admissionsUrl: "https://admissions.ecu.edu",
    city: "Greenville",
    state: "NC",
    region: "SOUTHEAST",
    control: "PUBLIC",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Pirates",
      baseballWebsiteUrl: "https://ecupirates.com/sports/baseball",
      division: "NCAA_D1",
      conference: "AAC",
    },
  },
  {
    name: "University of North Carolina Wilmington",
    slug: "university-of-north-carolina-wilmington",
    websiteUrl: "https://uncw.edu",
    admissionsUrl: "https://uncw.edu/admissions",
    city: "Wilmington",
    state: "NC",
    region: "SOUTHEAST",
    control: "PUBLIC",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Seahawks",
      baseballWebsiteUrl: "https://uncwsports.com/sports/baseball",
      division: "NCAA_D1",
      conference: "CAA",
    },
  },
  {
    name: "Wake Forest University",
    slug: "wake-forest-university",
    websiteUrl: "https://www.wfu.edu",
    admissionsUrl: "https://admissions.wfu.edu",
    city: "Winston-Salem",
    state: "NC",
    region: "SOUTHEAST",
    control: "PRIVATE",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Demon Deacons",
      baseballWebsiteUrl: "https://godeacs.com/sports/baseball",
      division: "NCAA_D1",
      conference: "ACC",
    },
  },
  {
    name: "High Point University",
    slug: "high-point-university",
    websiteUrl: "https://www.highpoint.edu",
    admissionsUrl: "https://www.highpoint.edu/admissions",
    city: "High Point",
    state: "NC",
    region: "SOUTHEAST",
    control: "PRIVATE",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Panthers",
      baseballWebsiteUrl: "https://highpointpanthers.com/sports/baseball",
      division: "NCAA_D1",
      conference: "Big South",
    },
  },
  {
    name: "Campbell University",
    slug: "campbell-university",
    websiteUrl: "https://www.campbell.edu",
    admissionsUrl: "https://www.campbell.edu/admissions",
    city: "Buies Creek",
    state: "NC",
    region: "SOUTHEAST",
    control: "PRIVATE",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Fighting Camels",
      baseballWebsiteUrl: "https://gocamels.com/sports/baseball",
      division: "NCAA_D1",
      conference: "CAA",
    },
  },
  {
    name: "Appalachian State University",
    slug: "appalachian-state-university",
    websiteUrl: "https://www.appstate.edu",
    admissionsUrl: "https://admissions.appstate.edu",
    city: "Boone",
    state: "NC",
    region: "SOUTHEAST",
    control: "PUBLIC",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Mountaineers",
      baseballWebsiteUrl: "https://appstatesports.com/sports/baseball",
      division: "NCAA_D1",
      conference: "Sun Belt",
    },
  },
  {
    name: "University of Georgia",
    slug: "university-of-georgia",
    websiteUrl: "https://www.uga.edu",
    admissionsUrl: "https://www.admissions.uga.edu",
    city: "Athens",
    state: "GA",
    region: "SOUTHEAST",
    control: "PUBLIC",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Bulldogs",
      baseballWebsiteUrl: "https://georgiadogs.com/sports/baseball",
      division: "NCAA_D1",
      conference: "SEC",
    },
  },
  {
    name: "Georgia Tech",
    slug: "georgia-tech",
    websiteUrl: "https://www.gatech.edu",
    admissionsUrl: "https://admission.gatech.edu",
    city: "Atlanta",
    state: "GA",
    region: "SOUTHEAST",
    control: "PUBLIC",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Yellow Jackets",
      baseballWebsiteUrl: "https://ramblinwreck.com/sports/m-basebl/",
      division: "NCAA_D1",
      conference: "ACC",
    },
  },
  {
    name: "Kennesaw State University",
    slug: "kennesaw-state-university",
    websiteUrl: "https://www.kennesaw.edu",
    admissionsUrl: "https://www.kennesaw.edu/admissions/",
    city: "Kennesaw",
    state: "GA",
    region: "SOUTHEAST",
    control: "PUBLIC",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Owls",
      baseballWebsiteUrl: "https://ksuowls.com/sports/baseball",
      division: "NCAA_D1",
      conference: "Conference USA",
    },
  },
  {
    name: "Mercer University",
    slug: "mercer-university",
    websiteUrl: "https://www.mercer.edu",
    admissionsUrl: "https://admissions.mercer.edu",
    city: "Macon",
    state: "GA",
    region: "SOUTHEAST",
    control: "PRIVATE",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Bears",
      baseballWebsiteUrl: "https://mercerbears.com/sports/baseball",
      division: "NCAA_D1",
      conference: "SoCon",
    },
  },
  {
    name: "University of Tennessee",
    slug: "university-of-tennessee",
    websiteUrl: "https://www.utk.edu",
    admissionsUrl: "https://admissions.utk.edu",
    city: "Knoxville",
    state: "TN",
    region: "SOUTHEAST",
    control: "PUBLIC",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Volunteers",
      baseballWebsiteUrl: "https://utsports.com/sports/baseball",
      division: "NCAA_D1",
      conference: "SEC",
    },
  },
  {
    name: "Vanderbilt University",
    slug: "vanderbilt-university",
    websiteUrl: "https://www.vanderbilt.edu",
    admissionsUrl: "https://admissions.vanderbilt.edu",
    city: "Nashville",
    state: "TN",
    region: "SOUTHEAST",
    control: "PRIVATE",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Commodores",
      baseballWebsiteUrl: "https://vucommodores.com/sports/baseball",
      division: "NCAA_D1",
      conference: "SEC",
    },
  },
  {
    name: "East Tennessee State University",
    slug: "east-tennessee-state-university",
    websiteUrl: "https://www.etsu.edu",
    admissionsUrl: "https://www.etsu.edu/admissions/",
    city: "Johnson City",
    state: "TN",
    region: "SOUTHEAST",
    control: "PUBLIC",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Buccaneers",
      baseballWebsiteUrl: "https://etsubucs.com/sports/baseball",
      division: "NCAA_D1",
      conference: "SoCon",
    },
  },
  {
    name: "University of Virginia",
    slug: "university-of-virginia",
    websiteUrl: "https://www.virginia.edu",
    admissionsUrl: "https://admission.virginia.edu",
    city: "Charlottesville",
    state: "VA",
    region: "SOUTHEAST",
    control: "PUBLIC",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Cavaliers",
      baseballWebsiteUrl: "https://virginiasports.com/sports/baseball",
      division: "NCAA_D1",
      conference: "ACC",
    },
  },
  {
    name: "Virginia Tech",
    slug: "virginia-tech",
    websiteUrl: "https://www.vt.edu",
    admissionsUrl: "https://www.vt.edu/admissions.html",
    city: "Blacksburg",
    state: "VA",
    region: "SOUTHEAST",
    control: "PUBLIC",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Hokies",
      baseballWebsiteUrl: "https://hokiesports.com/sports/baseball",
      division: "NCAA_D1",
      conference: "ACC",
    },
  },
  {
    name: "Liberty University",
    slug: "liberty-university",
    websiteUrl: "https://www.liberty.edu",
    admissionsUrl: "https://www.liberty.edu/residential/admissions/",
    city: "Lynchburg",
    state: "VA",
    region: "SOUTHEAST",
    control: "PRIVATE",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Flames",
      baseballWebsiteUrl: "https://libertyflames.com/sports/baseball",
      division: "NCAA_D1",
      conference: "Conference USA",
    },
  },
  {
    name: "James Madison University",
    slug: "james-madison-university",
    websiteUrl: "https://www.jmu.edu",
    admissionsUrl: "https://www.jmu.edu/admissions/",
    city: "Harrisonburg",
    state: "VA",
    region: "SOUTHEAST",
    control: "PUBLIC",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Dukes",
      baseballWebsiteUrl: "https://jmusports.com/sports/baseball",
      division: "NCAA_D1",
      conference: "Sun Belt",
    },
  },
    {
    name: "North Greenville University",
    slug: "north-greenville-university",
    websiteUrl: "https://ngu.edu",
    admissionsUrl: "https://ngu.edu/admissions/",
    city: "Tigerville",
    state: "SC",
    region: "SOUTHEAST",
    control: "PRIVATE",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Trailblazers",
      baseballWebsiteUrl: "https://nguathletics.com/sports/baseball",
      division: "NCAA_D2",
      conference: "Conference Carolinas",
    },
  },
  {
    name: "Lander University",
    slug: "lander-university",
    websiteUrl: "https://www.lander.edu",
    admissionsUrl: "https://www.lander.edu/admissions",
    city: "Greenwood",
    state: "SC",
    region: "SOUTHEAST",
    control: "PUBLIC",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Bearcats",
      baseballWebsiteUrl: "https://landerbearcats.com/sports/baseball",
      division: "NCAA_D2",
      conference: "Peach Belt Conference",
    },
  },
  {
    name: "Coker University",
    slug: "coker-university",
    websiteUrl: "https://www.coker.edu",
    admissionsUrl: "https://www.coker.edu/admissions/",
    city: "Hartsville",
    state: "SC",
    region: "SOUTHEAST",
    control: "PRIVATE",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Cobras",
      baseballWebsiteUrl: "https://cokercobras.com/sports/baseball",
      division: "NCAA_D2",
      conference: "South Atlantic Conference",
    },
  },
  {
    name: "Francis Marion University",
    slug: "francis-marion-university",
    websiteUrl: "https://www.fmarion.edu",
    admissionsUrl: "https://www.fmarion.edu/admissions/",
    city: "Florence",
    state: "SC",
    region: "SOUTHEAST",
    control: "PUBLIC",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Patriots",
      baseballWebsiteUrl: "https://fmupatriots.com/sports/baseball",
      division: "NCAA_D2",
      conference: "Conference Carolinas",
    },
  },
  {
    name: "Erskine College",
    slug: "erskine-college",
    websiteUrl: "https://www.erskine.edu",
    admissionsUrl: "https://www.erskine.edu/admissions/",
    city: "Due West",
    state: "SC",
    region: "SOUTHEAST",
    control: "PRIVATE",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Flying Fleet",
      baseballWebsiteUrl: "https://erskinesports.com/sports/baseball",
      division: "NCAA_D2",
      conference: "Conference Carolinas",
    },
  },
  {
    name: "Belmont Abbey College",
    slug: "belmont-abbey-college",
    websiteUrl: "https://belmontabbeycollege.edu",
    admissionsUrl: "https://belmontabbeycollege.edu/admissions/",
    city: "Belmont",
    state: "NC",
    region: "SOUTHEAST",
    control: "PRIVATE",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Crusaders",
      baseballWebsiteUrl: "https://abbeyathletics.com/sports/baseball",
      division: "NCAA_D2",
      conference: "Conference Carolinas",
    },
  },
  {
    name: "Queens University of Charlotte",
    slug: "queens-university-of-charlotte",
    websiteUrl: "https://www.queens.edu",
    admissionsUrl: "https://www.queens.edu/admissions/",
    city: "Charlotte",
    state: "NC",
    region: "SOUTHEAST",
    control: "PRIVATE",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Royals",
      baseballWebsiteUrl: "https://queensathletics.com/sports/baseball",
      division: "NCAA_D1",
      conference: "ASUN",
    },
  },
  {
    name: "Wingate University",
    slug: "wingate-university",
    websiteUrl: "https://www.wingate.edu",
    admissionsUrl: "https://www.wingate.edu/admissions",
    city: "Wingate",
    state: "NC",
    region: "SOUTHEAST",
    control: "PRIVATE",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Bulldogs",
      baseballWebsiteUrl: "https://wingatebulldogs.com/sports/baseball",
      division: "NCAA_D2",
      conference: "South Atlantic Conference",
    },
  },
  {
    name: "Catawba College",
    slug: "catawba-college",
    websiteUrl: "https://www.catawba.edu",
    admissionsUrl: "https://www.catawba.edu/admissions/",
    city: "Salisbury",
    state: "NC",
    region: "SOUTHEAST",
    control: "PRIVATE",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Catawba Indians",
      baseballWebsiteUrl: "https://gocatawbaindians.com/sports/baseball",
      division: "NCAA_D2",
      conference: "South Atlantic Conference",
    },
  },
  {
    name: "Mount Olive University",
    slug: "mount-olive-university",
    websiteUrl: "https://umo.edu",
    admissionsUrl: "https://umo.edu/admissions/",
    city: "Mount Olive",
    state: "NC",
    region: "SOUTHEAST",
    control: "PRIVATE",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Trojans",
      baseballWebsiteUrl: "https://umotrojans.com/sports/baseball",
      division: "NCAA_D2",
      conference: "Conference Carolinas",
    },
  },
  {
    name: "Pfeiffer University",
    slug: "pfeiffer-university",
    websiteUrl: "https://www.pfeiffer.edu",
    admissionsUrl: "https://www.pfeiffer.edu/admissions/",
    city: "Misenheimer",
    state: "NC",
    region: "SOUTHEAST",
    control: "PRIVATE",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Falcons",
      baseballWebsiteUrl: "https://gofalconsports.com/sports/baseball",
      division: "NCAA_D3",
      conference: "USA South Athletic Conference",
    },
  },
  {
    name: "Brevard College",
    slug: "brevard-college",
    websiteUrl: "https://brevard.edu",
    admissionsUrl: "https://brevard.edu/admissions/",
    city: "Brevard",
    state: "NC",
    region: "SOUTHEAST",
    control: "PRIVATE",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Tornados",
      baseballWebsiteUrl: "https://bctornados.com/sports/baseball",
      division: "NCAA_D3",
      conference: "USA South Athletic Conference",
    },
  },
  {
    name: "Methodist University",
    slug: "methodist-university",
    websiteUrl: "https://www.methodist.edu",
    admissionsUrl: "https://www.methodist.edu/admissions/",
    city: "Fayetteville",
    state: "NC",
    region: "SOUTHEAST",
    control: "PRIVATE",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Monarchs",
      baseballWebsiteUrl: "https://mumonarchs.com/sports/baseball",
      division: "NCAA_D3",
      conference: "USA South Athletic Conference",
    },
  },
  {
    name: "LaGrange College",
    slug: "lagrange-college",
    websiteUrl: "https://www.lagrange.edu",
    admissionsUrl: "https://www.lagrange.edu/admission/",
    city: "LaGrange",
    state: "GA",
    region: "SOUTHEAST",
    control: "PRIVATE",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Panthers",
      baseballWebsiteUrl: "https://lagrangepanthers.com/sports/baseball",
      division: "NCAA_D3",
      conference: "Collegiate Conference of the South",
    },
  },
  {
    name: "Piedmont University",
    slug: "piedmont-university",
    websiteUrl: "https://www.piedmont.edu",
    admissionsUrl: "https://www.piedmont.edu/admissions-aid/",
    city: "Demorest",
    state: "GA",
    region: "SOUTHEAST",
    control: "PRIVATE",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Lions",
      baseballWebsiteUrl: "https://piedmontlions.com/sports/baseball",
      division: "NCAA_D3",
      conference: "Collegiate Conference of the South",
    },
  },
  {
    name: "Reinhardt University",
    slug: "reinhardt-university",
    websiteUrl: "https://www.reinhardt.edu",
    admissionsUrl: "https://www.reinhardt.edu/admissions/",
    city: "Waleska",
    state: "GA",
    region: "SOUTHEAST",
    control: "PRIVATE",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Eagles",
      baseballWebsiteUrl: "https://reinhardteagles.com/sports/baseball",
      division: "NAIA",
      conference: "Appalachian Athletic Conference",
    },
  },
  {
    name: "Georgia Gwinnett College",
    slug: "georgia-gwinnett-college",
    websiteUrl: "https://www.ggc.edu",
    admissionsUrl: "https://www.ggc.edu/admissions",
    city: "Lawrenceville",
    state: "GA",
    region: "SOUTHEAST",
    control: "PUBLIC",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Grizzlies",
      baseballWebsiteUrl: "https://ggcathletics.com/sports/baseball",
      division: "NAIA",
      conference: "Continental Athletic Conference",
    },
  },
  {
    name: "Bryan College",
    slug: "bryan-college",
    websiteUrl: "https://www.bryan.edu",
    admissionsUrl: "https://www.bryan.edu/admissions/",
    city: "Dayton",
    state: "TN",
    region: "SOUTHEAST",
    control: "PRIVATE",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Lions",
      baseballWebsiteUrl: "https://bryanlions.com/sports/baseball",
      division: "NAIA",
      conference: "Appalachian Athletic Conference",
    },
  },
  {
    name: "Tennessee Wesleyan University",
    slug: "tennessee-wesleyan-university",
    websiteUrl: "https://www.tnwesleyan.edu",
    admissionsUrl: "https://www.tnwesleyan.edu/admissions/",
    city: "Athens",
    state: "TN",
    region: "SOUTHEAST",
    control: "PRIVATE",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Bulldogs",
      baseballWebsiteUrl: "https://twbulldogs.com/sports/baseball",
      division: "NAIA",
      conference: "Appalachian Athletic Conference",
    },
  },
  {
    name: "Emory & Henry University",
    slug: "emory-and-henry-university",
    websiteUrl: "https://www.ehc.edu",
    admissionsUrl: "https://www.ehc.edu/admissions/",
    city: "Emory",
    state: "VA",
    region: "SOUTHEAST",
    control: "PRIVATE",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Wasps",
      baseballWebsiteUrl: "https://gowasps.com/sports/baseball",
      division: "NCAA_D2",
      conference: "South Atlantic Conference",
    },
  },
  {
    name: "Randolph-Macon College",
    slug: "randolph-macon-college",
    websiteUrl: "https://www.rmc.edu",
    admissionsUrl: "https://www.rmc.edu/admissions/",
    city: "Ashland",
    state: "VA",
    region: "SOUTHEAST",
    control: "PRIVATE",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Yellow Jackets",
      baseballWebsiteUrl: "https://rmcathletics.com/sports/baseball",
      division: "NCAA_D3",
      conference: "Old Dominion Athletic Conference",
    },
  },
  {
    name: "Patrick & Henry Community College",
    slug: "patrick-and-henry-community-college",
    websiteUrl: "https://www.patrickhenry.edu",
    admissionsUrl: "https://www.patrickhenry.edu/admissions",
    city: "Martinsville",
    state: "VA",
    region: "SOUTHEAST",
    control: "PUBLIC",
    schoolType: "COMMUNITY_COLLEGE",
    baseball: {
      nickname: "Patriots",
      baseballWebsiteUrl: "https://phccsports.com/sports/bsb",
      division: "NJCAA_D2",
      conference: "NJCAA Region 10",
    },
  },
  {
    name: "Gaston College",
    slug: "gaston-college",
    websiteUrl: "https://www.gaston.edu",
    admissionsUrl: "https://www.gaston.edu/admissions/",
    city: "Dallas",
    state: "NC",
    region: "SOUTHEAST",
    control: "PUBLIC",
    schoolType: "COMMUNITY_COLLEGE",
    baseball: {
      nickname: "Rhinos",
      baseballWebsiteUrl: "https://gcrhinos.com/sports/bsb",
      division: "NJCAA_D1",
      conference: "NJCAA Region 10",
    },
  },
  {
    name: "Florence-Darlington Technical College",
    slug: "florence-darlington-technical-college",
    websiteUrl: "https://www.fdtc.edu",
    admissionsUrl: "https://www.fdtc.edu/admissions",
    city: "Florence",
    state: "SC",
    region: "SOUTHEAST",
    control: "PUBLIC",
    schoolType: "COMMUNITY_COLLEGE",
    baseball: {
      nickname: "Stingers",
      baseballWebsiteUrl: "https://stingersathletics.com/sports/bsb",
      division: "NJCAA_D1",
      conference: "NJCAA Region 10",
    },
  },
    {
    name: "Anderson University",
    slug: "anderson-university-sc",
    websiteUrl: "https://andersonuniversity.edu",
    admissionsUrl: "https://andersonuniversity.edu/admission-aid/",
    city: "Anderson",
    state: "SC",
    region: "SOUTHEAST",
    control: "PRIVATE",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Trojans",
      baseballWebsiteUrl: "https://autrojans.com/sports/baseball",
      division: "NCAA_D2",
      conference: "South Atlantic Conference",
    },
  },
  {
    name: "Newberry College",
    slug: "newberry-college",
    websiteUrl: "https://www.newberry.edu",
    admissionsUrl: "https://www.newberry.edu/admissions",
    city: "Newberry",
    state: "SC",
    region: "SOUTHEAST",
    control: "PRIVATE",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Wolves",
      baseballWebsiteUrl: "https://newberrywolves.com/sports/baseball",
      division: "NCAA_D2",
      conference: "South Atlantic Conference",
    },
  },
  {
    name: "Limestone University",
    slug: "limestone-university",
    websiteUrl: "https://www.limestone.edu",
    admissionsUrl: "https://www.limestone.edu/admissions",
    city: "Gaffney",
    state: "SC",
    region: "SOUTHEAST",
    control: "PRIVATE",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Saints",
      baseballWebsiteUrl: "https://golimestonesaints.com/sports/baseball",
      division: "NCAA_D2",
      conference: "South Atlantic Conference",
    },
  },
  {
    name: "Southern Wesleyan University",
    slug: "southern-wesleyan-university",
    websiteUrl: "https://www.swu.edu",
    admissionsUrl: "https://www.swu.edu/admissions/",
    city: "Central",
    state: "SC",
    region: "SOUTHEAST",
    control: "PRIVATE",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Warriors",
      baseballWebsiteUrl: "https://swuathletics.com/sports/baseball",
      division: "NCAA_D2",
      conference: "Conference Carolinas",
    },
  },
  {
    name: "Barton College",
    slug: "barton-college",
    websiteUrl: "https://www.barton.edu",
    admissionsUrl: "https://www.barton.edu/admissions/",
    city: "Wilson",
    state: "NC",
    region: "SOUTHEAST",
    control: "PRIVATE",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Bulldogs",
      baseballWebsiteUrl: "https://bartonbulldogs.com/sports/baseball",
      division: "NCAA_D2",
      conference: "Conference Carolinas",
    },
  },
  {
    name: "UNC Pembroke",
    slug: "unc-pembroke",
    websiteUrl: "https://www.uncp.edu",
    admissionsUrl: "https://www.uncp.edu/admissions",
    city: "Pembroke",
    state: "NC",
    region: "SOUTHEAST",
    control: "PUBLIC",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Braves",
      baseballWebsiteUrl: "https://uncpbraves.com/sports/baseball",
      division: "NCAA_D2",
      conference: "Conference Carolinas",
    },
  },
  {
    name: "Lenoir-Rhyne University",
    slug: "lenoir-rhyne-university",
    websiteUrl: "https://www.lr.edu",
    admissionsUrl: "https://www.lr.edu/admission",
    city: "Hickory",
    state: "NC",
    region: "SOUTHEAST",
    control: "PRIVATE",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Bears",
      baseballWebsiteUrl: "https://lrbears.com/sports/baseball",
      division: "NCAA_D2",
      conference: "South Atlantic Conference",
    },
  },
  {
    name: "Mars Hill University",
    slug: "mars-hill-university",
    websiteUrl: "https://www.mhu.edu",
    admissionsUrl: "https://www.mhu.edu/admissions/",
    city: "Mars Hill",
    state: "NC",
    region: "SOUTHEAST",
    control: "PRIVATE",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Lions",
      baseballWebsiteUrl: "https://marshilllions.com/sports/baseball",
      division: "NCAA_D2",
      conference: "South Atlantic Conference",
    },
  },
  {
    name: "Lees-McRae College",
    slug: "lees-mcrae-college",
    websiteUrl: "https://www.lmc.edu",
    admissionsUrl: "https://www.lmc.edu/admission/",
    city: "Banner Elk",
    state: "NC",
    region: "SOUTHEAST",
    control: "PRIVATE",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Bobcats",
      baseballWebsiteUrl: "https://lmcbobcats.com/sports/baseball",
      division: "NCAA_D2",
      conference: "Conference Carolinas",
    },
  },
  {
    name: "Carson-Newman University",
    slug: "carson-newman-university",
    websiteUrl: "https://www.cn.edu",
    admissionsUrl: "https://www.cn.edu/admissions/",
    city: "Jefferson City",
    state: "TN",
    region: "SOUTHEAST",
    control: "PRIVATE",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Eagles",
      baseballWebsiteUrl: "https://cneagles.com/sports/baseball",
      division: "NCAA_D2",
      conference: "South Atlantic Conference",
    },
  },
  {
    name: "Lincoln Memorial University",
    slug: "lincoln-memorial-university",
    websiteUrl: "https://www.lmunet.edu",
    admissionsUrl: "https://www.lmunet.edu/admissions",
    city: "Harrogate",
    state: "TN",
    region: "SOUTHEAST",
    control: "PRIVATE",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Railsplitters",
      baseballWebsiteUrl: "https://lmurailsplitters.com/sports/baseball",
      division: "NCAA_D2",
      conference: "South Atlantic Conference",
    },
  },
  {
    name: "Tusculum University",
    slug: "tusculum-university",
    websiteUrl: "https://site.tusculum.edu",
    admissionsUrl: "https://site.tusculum.edu/admission/",
    city: "Greeneville",
    state: "TN",
    region: "SOUTHEAST",
    control: "PRIVATE",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Pioneers",
      baseballWebsiteUrl: "https://tusculumpioneers.com/sports/baseball",
      division: "NCAA_D2",
      conference: "South Atlantic Conference",
    },
  },
  {
    name: "UVA Wise",
    slug: "uva-wise",
    websiteUrl: "https://www.uvawise.edu",
    admissionsUrl: "https://www.uvawise.edu/admissions",
    city: "Wise",
    state: "VA",
    region: "SOUTHEAST",
    control: "PUBLIC",
    schoolType: "FOUR_YEAR",
    baseball: {
      nickname: "Cavaliers",
      baseballWebsiteUrl: "https://uvawisecavs.com/sports/baseball",
      division: "NCAA_D2",
      conference: "South Atlantic Conference",
    },
  },
  {
    name: "Cleveland Community College",
    slug: "cleveland-community-college",
    websiteUrl: "https://clevelandcc.edu",
    admissionsUrl: "https://clevelandcc.edu/admissions/",
    city: "Shelby",
    state: "NC",
    region: "SOUTHEAST",
    control: "PUBLIC",
    schoolType: "COMMUNITY_COLLEGE",
    baseball: {
      nickname: "Yetis",
      baseballWebsiteUrl: "https://clevelandyetis.com/sports/bsb",
      division: "NJCAA_D2",
      conference: "NJCAA Region 10",
    },
  },
  {
    name: "Louisburg College",
    slug: "louisburg-college",
    websiteUrl: "https://www.louisburg.edu",
    admissionsUrl: "https://www.louisburg.edu/admissions/",
    city: "Louisburg",
    state: "NC",
    region: "SOUTHEAST",
    control: "PRIVATE",
    schoolType: "JUNIOR_COLLEGE",
    baseball: {
      nickname: "Hurricanes",
      baseballWebsiteUrl: "https://www.lchurricanes.com/sports/bsb",
      division: "NJCAA_D1",
      conference: "NJCAA Region 10",
    },
  },
];

async function main() {
  for (const item of colleges) {
    const college = await prisma.college.upsert({
      where: { slug: item.slug },
      update: {
        name: item.name,
        websiteUrl: item.websiteUrl,
        admissionsUrl: item.admissionsUrl,
        academicsUrl: item.academicsUrl,
        majorsUrl: item.majorsUrl,
        applicationUrl: item.applicationUrl,
        financialAidUrl: item.financialAidUrl,
        city: item.city,
        state: item.state,
        region: item.region,
        control: item.control,
        schoolType: item.schoolType,
        tuitionInState: item.tuitionInState,
        tuitionOutOfState: item.tuitionOutOfState,
        tuitionInternational: item.tuitionInternational,
        tuitionYear: item.tuitionYear,
      },
      create: {
        name: item.name,
        slug: item.slug,
        websiteUrl: item.websiteUrl,
        admissionsUrl: item.admissionsUrl,
        city: item.city,
        state: item.state,
        region: item.region,
        control: item.control,
      },
    });

    if (item.baseball) {
      await prisma.collegeBaseballProgram.upsert({
        where: { collegeId: college.id },
        update: {
          nickname: item.baseball.nickname,
          baseballWebsiteUrl: item.baseball.baseballWebsiteUrl,
          division: item.baseball.division,
          conference: item.baseball.conference,
          rosterUrl: item.baseball.rosterUrl,
          questionnaireUrl: item.baseball.questionnaireUrl,
        },
        create: {
          collegeId: college.id,
          nickname: item.baseball.nickname,
          baseballWebsiteUrl: item.baseball.baseballWebsiteUrl,
          division: item.baseball.division,
          conference: item.baseball.conference,
          rosterUrl: item.baseball.rosterUrl,
          questionnaireUrl: item.baseball.questionnaireUrl,
        },
      });
    }

    console.log(`Seeded: ${item.name}`);
  }
}

main()
  .catch((err) => {
    console.error("SEED_COLLEGES_ERROR", err);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });